### PR TITLE
feat: add lodash modules as a dependency instead of full lodash

### PR DESCRIPTION
**Pull request by andreoav**

### CODE REVIEW

**Comment by jquense** [comment]
Thanks for the PR. The reason we didn't do this originally is that using individual packages is likely to result in _larger_ bundles for consumers since most folks use the plain `lodash` package, so rather than get deduped `has` usage from someone using `lodash` and `lodash.has` you end up with two packages. vs cherry picking from the module like we do here only requires the specific one we need but in the context of the main package so anyone else using `lodash` will not duplicate the functions we're using

**Comment by andreoav** [comment]
@jquense And there is a way to handle ppl that don't use lodash at all?

I use next.js and I have many splits, but everytime I need yup somewhere, I get the full lodash in that split.

**Comment by jquense** [comment]
are you talking about downloading all of lodash or all of lodash being included in in a bundle? The latter won't happen, only the modules we cherry pick are included see #359 for more discussion around install size

**Comment by divmgl** [comment]
To add to this, this is no longer necessary with tree shaking. Instead of bringing in each individual module as a package you can refer directly to a file inside of `lodash` and Webpack should do the rest:

```
import pick from 'lodash/pick'
```

**Comment by jquense** [comment]
We already do that that yeah

**Pull request closed without merging**
