### PR TITLE
Introduce airbnb eslint config

### PR DESCRIPTION
**Pull request by ctavan**
This one is based on #115.

I felt that a stricter eslint config would be beneficial to enforce certain styles throughout the code base.

In previous projects I found the [Airbnb eslint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) to be pretty reasonable.

I have also upgraded all dependencies and removed some unused dependencies in this branch.

### CODE REVIEW

**Comment by jquense** [comment]
Hey there, thanks for the PR, I'm pretty happy with the existing lint style, I prefer much less prescriptive style, hence the personal config

**Comment by rosskevin** [comment]
I realize it is your prerogative @jquense, but in the spirit of fostering a community and a willing group of contributors, I ask that you reconsider your personal configs in favor of more prevalent general open source pseudo standards, etc.

As-is, it seems you are the only one that maintains yup and react-formal, and I would only think it a good thing if you can start getting quality PRs from the community that lead to better CI and community involvement. 

Thanks again for your great work in these projects.

**Comment by ctavan** [comment]
Hey @jquense, I can understand that linting-configs are always up to personal preference.

However similar to what @rosskevin pointed out, I found it increasingly difficult to incorporate contributions from many different people to open source projects where there was not an extensive suite of tests and enforced linting rules.

I found [this blog post by Mikeal Rogers](https://medium.com/@mikeal/modern-modules-d99b6867b8f1) pretty inspiring in that regard, in particular:

> I no longer believe that I can handle even moderate maintenance burden from modules I create.

[...]

> In order to offset this burden I adopted a set of practices pioneered by the Hoodie team using some of the infrastructure that has spun out of that community.
> * I no longer do any releases by hand, releases are entirely automated with semantic release and run on every checkin.
> * I don’t release a project until it has 100% test coverage and going forward test coverage cannot drop below 100%. This is easy to do when you start a module but incredibly difficult to achieve after a module has matured.
> * I have npm scripts for creating nice commit messages, running coverage reports, automating git hooks for verification, etc. This helps me and other contributors align with the tools.
> * All projects have greenkeeper enabled, automating all dependency upgrades.

I really like this library since it has an interface that is equally aspiring as the one of `joi`, however it's much more lightweight. As I've said earlier I'm really eager to contribute substantial improvements to this library (support for sync validations, performance improvements, etc.) and given the pull requests I reckon that there are other people willing to contribute as well.

Even mid-term I believe that having an extensive set of tests and linting rules in place will be a prerequisite for a stable evolution of this library.

**Comment by jquense** [comment]
The current config catches bugs and leaves style mostly unspecified. I hear you folks however these projects are places I enjoy having fewer constraints and room for whatever code style I feel like, where I never have to write an eslint pragma.  I am equally nonchalant about contributions so if you want to write something more strict go for it. I don't however think it makes that much of a difference in contributions, folks don't contribute here because it's small and mostly used by me :P

**Comment by rosskevin** [comment]
I can say that @ctavan and I are serious users, and I am writing software for multiple businesses that depend on yup and react-formal (which depend on your other projects).

Are you saying you would prefer us fork these because you would like to simply keep this a personal project?  It's ok if you do, I just default to being loyal to the author first, and only do that as a last resort. Thanks again

**Comment by jquense** [comment]
No I don't think y'all should have to fork, but the code style of these projects shouldn't matter to that. We aren't talking avoiding bugs we're picking brace and semicolon preferences. I'm glad y'all use the libraries and I'm more than happy to take feedback and make sure we are providing stable releases. To that end tho I generally find airbnb style guide unhelpful, pedantic and constricting.  It to be rude but I don't think my wanting to maintain the eslint config I prefer amounts to being contributor hostile.

**Comment by rosskevin** [comment]
@jquense it is not limited to just eslint.  I perceive your repos as a bit anti-contributor due to what you referred to as a _nonchalant_ attitude.  So perhaps the number of contributors is a bit chicken and egg problem?  You may not have a wealth of contributions, because perhaps you aren't fostering them by sending the signals that most look for in a project.  For example, PRs going months or over a year, without being merged and without providing any feedback is a real indicator to me, and I assume most, about willingness to accept contributions (see react-formal).

If you are giving indications that PRs won't get merged, why would someone put forth the effort to create one a new PR?

In any case, _this is all your prerogative_ and I accept that, and again, thank you very much for putting your great work out here.

I would like to see yup and react-formal take a more serious direction, and I'd like to see contributions grow.  I support doing so here, or in a fork, but of course I would support the effort here if you were to decide that nonchalance is perhaps something that you would be willing to put behind you.

@ctavan feel free to ping me if you would like to discuss further, my email is in my profile.

**Comment by jquense** [comment]
ok first of all, I also have a large professional stake in these libraries and use them extensively in my job. I appreciate that ya'll would like there to be more contributors to my projects, but showing up to someones house to rearrange there furniture without notice is not the best way to do that. If ya'll want to be involved or take an active stake in the direction of these libraries then the best way to do that is not try and move the main contributor's cheese and accuse them of being  anti-collaboration. A better approach would be to ask where contributors are needed, write substantive PR's, and  overall try and help out instead of demanding the project take a shape you feel is appropriate, or threatening to fork. 

@rosskevin I am extremely glad that you find value and utility in these projects, and i think i've been helpful and attentive to your needs in the past, and hope that you continue to use them (and i'm happy to continue to help out). Please try to remember that you are benefiting from my free labor.

**Comment by rosskevin** [comment]
@jquense I think I've been fair and factual when framing my criticisms.  I repeated your words and the used facts about your repos and my PRs (e.g. [a simple PR that has never received comment and never merged](https://github.com/jquense/react-formal/pull/124)).  And in all my responses, I've thanked you for your work, because I do benefit, and I am sincerely thankful.  

I am a significant contributor to the projects I use, and you might say that yup and react-formal are the outliers because it doesn't seem my contributions would be accepted, simply based on the current state of the open PRs in react-formal (and the lack of acceptance of the simple ones including mine).

I do not believe I've said anything with intent to offend, and I take care not to do so.  If you have taken offense, please be assured that I did not intend it.

And again, thank you for taking time to respond, but I don't think you've addressed any of my points other than (this is my perception) to say that I should stay quiet and just be thankful.

So, I'm surely thankful, I'm just not so versed at staying quiet.  Now that I know where you stand, I'll do my best to fit in or find another path.

**Comment by jquense** [comment]
@rosskevin I honestly sorry your PR has been sitting for so long, I field 100s of github notifications a week, across a lot of repos, sometimes PRs and issues fall through the cracks, and providing feedback and support is not my full time job, especially when they are maintenance things. You can ping the PR again if I don't respond promptly. To be fair though I am generally very responsive on all your issues, and try to take time to work through issues or feedback with you. I am glad that you are thankful and happy to work with you. I'm much more amenable to suggestions when they feel like attempts to help instead of disappointment in my performance.

**Pull request closed without merging**
