### PR TITLE
Added label() options

### PR DESCRIPTION
**Pull request by paulgraves**
As requested in issue Add .label() option #13

### CODE REVIEW

**Comment by jquense** [comment]
thanks! can you also add a documentation entry in mixed for the label?

**Comment by paulgraves** [comment]
Ok, added.

**Comment by jquense** [comment]
thanks a lot!

**Comment by paulgraves** [comment]
Hi, can you do a new release now my pull request has been merged? I want to change my project back to use the main version of yup rather than my fork. Thanks

**Pull request merged**
