### PR TITLE
feat: sequential schema validation

### PR DESCRIPTION
**Pull request by codepunkt**
This is a first take on sequential schema validation (see #256). Any comments are welcome! 👍

### CODE REVIEW

**Comment by ctaylo21** [comment]
@codepunkt Any updates on this? Would love to to have this feature.

**Comment by ematipico** [comment]
Any chance to get some updates on this PR? @jquense 
This feature looks promising and really needed

**Comment by marcstreeter** [comment]
@codepunkt would you mind adding some documentation where appropriate? or is that generated automatically here?

**Comment by diogocapela** [comment]
Any updates?

**Comment by andrey-hohlov** [comment]
Any updates?

**Comment by codepunkt** [comment]
I haven't used this package for years. Someone maintainer should have a look at this and decide to merge or not to merge - there's not more i can do.

**Comment by jquense** [comment]
thanks @codepunkt for your work. I'm gonna close for now and when there is space or time to think through this again, definitely will use your work as a resource

**Comment by tjbulick** [comment]
Same here, I'm also waiting for this feature... 
I think it would be very handy for many people to have an ability to check their values stepwise
So any updates or at least temporary solution?

**Comment by resting** [comment]
Am wondering the same thing today, can we relook into this?

**Pull request closed without merging**
