### PR TITLE
Fix: Add missing functions to lazy

### PR DESCRIPTION
**Pull request by chasecaleb**
Add missing functions to `Lazy`:
- `isValid`
- `isValidSync`
- `isType`

These are all validation functions that have a `value` parameter, so it makes sense for `Lazy` to wrap them.

### CODE REVIEW

**Comment by chasecaleb** [comment]
Hi @jquense, just wondering if you've seen this PR since it's been a month. Do you have a sec to look at it? Thanks.

**Comment by chasecaleb** [comment]
Hi @jquense, do you accept PRs for this project?

**Comment by chasecaleb** [comment]
@jquense I'd like to stop depending on my own fork... are you interested in this PR? It looks like you've since converted the file in question to TypeScript, I'm happy to redo my change -- or you're welcome to make the change yourself since it's trivial.

If you don't want to accept the PR then feel free to say so, but I've put time into this and would appreciate a response so that I can decide what to do for my own project that depends on this.

**Comment by jquense** [comment]
Hi @chasecaleb sorry, it's not a great excuse but  GH is terrible to keeping track of pending work across lots of repos. Sorry. If you want to rebase this happy to accept it

**Comment by chasecaleb** [comment]
@jquense That's okay, I completely understand missing notifications. Thanks for getting back to me!

Anyways... apparently Github "helpfully" closes the MR for you if you start rewriting history, and now it isn't picking up my new commit. I don't really know what's going on there so I made a new PR that's ready for you: #1148 . Sorry, I'm used to using Gitlab.

**Pull request closed without merging**
